# $FreeBSD$

PORTNAME=	rgen
PORTVERSION=	0.8.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	puppet@FreeBSD.org
COMMENT=	Roby modeling and generator framework

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
